### ISSUE TITLE
Add UI to bail out of submission modal

### ISSUE THREAD

**Issue by harvardx-tech-ops** [HarvardX/playremote#12]
Per Bharat: When I start creating an event and want to cancel it the only option is to continue with back buttons. Perhaps a simple “Cancel Event” at the bottom may be useful.

**Comment by lduarte1991** [comment]
Added a "Reset form" instead of "cancel event" which i'm assuming is ok, unless that wording was chosen deliberately?

**Comment by harvardx-tech-ops** [comment]
In looking at this, clicking either "Upcoming" or "Calendar" will close the submit form without saving changes at any point in the submission process and cancel the submission in the process. We have added a "reset" button so one can clear the form and start over without leaving the submission form and coming back.
