### ISSUE TITLE
Rate limit event submissions

### ISSUE THREAD

**Issue by dpmccabe** [HarvardX/playremote#29]
Rate limiting should be done in API based on number of events submitted in last X seconds/minutes. Maybe with some kind of exponential backoff. Should only be triggered when it's obvious automation is being used.

API returns a 429 error if the submission is disallowed, which results in a custom error displayed on the front-end.

**Comment by tingleyd** [comment]
This will be important to do, but given things are behind HarvardKey, probably don't need this for initial release. (Unless its trivial to do)
