### ISSUE TITLE
Filter State Lost when moving between Calendar views (Day, week, month)

### ISSUE THREAD

**Issue by harvardx-tech-ops** [HarvardX/playremote#4]
Maintain filter state.

**Comment by lduarte1991** [comment]
@harvardx-tech-ops So there's a bit of an issue with this: Filters are determined by the events currently in place. So if you have "University-wide" selected and you switch to the following week, those events may not have have any "university-wide" and thus the filter would not exist. how should that be handled?

**Comment by harvardx-tech-ops** [comment]
Third color (grayed out, overlay text of "none this week"? What's doable?

**Comment by lduarte1991** [comment]
Well i search through the filters and display the ones that are there. it doesn't know about filters that aren't there at that point.

**Comment by dpmccabe** [comment]
Could we just use the /event/options endpoint to load options for the filters box? Feel like this would be better UX since e.g. an HBS student might come to the site, not see an HBS filter for the current timeframe, and be frustrated that the app seems not to support HBS.
