### ISSUE TITLE
 LOAD MORE button remains, even though there are no more events to display. 

### ISSUE THREAD

**Issue by harvardx-tech-ops** [HarvardX/playremote#5]
## Fixed in dev

**Comment by lduarte1991** [comment]
@dpmccabe verify this was something you fixed on friday and close? thanks!

**Comment by dpmccabe** [comment]
Actually I don't remember working on this at all

**Comment by lduarte1991** [comment]
Oops, that was definitely me. I think it had to do with a Load more button appearing during search cause i added a "searching" boolean to test for that. I think i remembered you saying it got pushed to devo during the discussion with dustin EOD friday. my bad. it's done
